In [135]:
TEST = False
DEBUG = False

X = """11111
19991
19191
19991
11111"""

X = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

if not TEST:
    with open("aoc_11_input.txt", "r") as f:
        X = f.read().strip()
X = X.split("\n")

import numpy as np

data = []
for line in X:
    ll = []
    for i in line:
        ll.append( int(i) )
    data.append(ll)


OctopusGrid2 = np.array( data )
height,width = OctopusGrid2.shape


In [136]:
#Part1
OctopusGrid = OctopusGrid2
FlashGrid = np.array([[1,1,1],[1,0,1],[1,1,1]])


FLASH = 0

print(FlashGrid)
print()
print(OctopusGrid)
print()

for i in range(0,1000):
    #increment
    flashed = np.ones((height,width))
    OctopusGrid += 1
    
    y,x = np.where(OctopusGrid>9)
    coords = list(zip(y,x))
    while len(coords) > 0:
        y,x = coords[0]
        del coords[0]
        FLASH += 1
        yMin = 0 if y==0 else -1
        yMax = 0 if y==height-1 else 1
        xMin = 0 if x==0 else -1
        xMax = 0 if x==width-1 else 1

        for yy in range(y+yMin,y+yMax+1):
            for xx in range(x+xMin, x+xMax+1):
                OctopusGrid[yy][xx] += 1
        flashed[y][x] = 0
        OctopusGrid = OctopusGrid * flashed 
        
        if len(coords) == 0:
            y,x = np.where(OctopusGrid>9)
            coords = list(zip(y,x))
    if np.sum(flashed) == 0:
        print("SYNCHED")
        print(i)
        break
    if (i % 10) == 0:
        print()
        print(OctopusGrid)
        print()
    
    #calculate flash
print(FLASH)

[[1 1 1]
 [1 0 1]
 [1 1 1]]

[[4 8 7 1 2 5 2 7 6 3]
 [8 5 3 3 4 2 8 1 7 3]
 [7 1 8 2 1 8 6 8 1 3]
 [2 1 2 8 4 4 1 5 4 1]
 [3 7 2 2 2 7 2 2 7 2]
 [8 7 5 1 6 8 3 4 4 3]
 [3 1 3 5 5 7 1 1 5 3]
 [5 8 1 6 3 2 1 5 7 2]
 [2 6 5 1 3 4 7 2 7 1]
 [7 7 8 8 1 5 4 2 5 2]]


[[5 9 8 2 3 6 3 8 7 4]
 [9 6 4 4 5 3 9 2 8 4]
 [8 2 9 3 2 9 7 9 2 4]
 [3 2 3 9 5 5 2 6 5 2]
 [4 8 3 3 3 8 3 3 8 3]
 [9 8 6 2 7 9 4 5 5 4]
 [4 2 4 6 6 8 2 2 6 4]
 [6 9 2 7 4 3 2 6 8 3]
 [3 7 6 2 4 5 8 3 8 2]
 [8 8 9 9 2 6 5 3 6 3]]


[[1. 4. 4. 1. 1. 4. 3. 6. 6. 1.]
 [4. 4. 4. 5. 7. 9. 1. 9. 1. 1.]
 [4. 4. 3. 3. 4. 1. 1. 1. 7. 1.]
 [2. 5. 3. 3. 4. 5. 6. 6. 8. 1.]
 [2. 9. 3. 3. 3. 3. 3. 3. 6. 1.]
 [7. 8. 8. 3. 8. 9. 5. 5. 7. 1.]
 [3. 6. 8. 7. 7. 9. 2. 2. 9. 1.]
 [3. 1. 4. 9. 5. 2. 2. 2. 5. 2.]
 [3. 7. 4. 4. 7. 2. 2. 2. 4. 0.]
 [2. 5. 3. 4. 2. 2. 2. 2. 3. 9.]]


[[7. 1. 2. 0. 0. 2. 1. 1. 1. 6.]
 [1. 1. 2. 3. 3. 2. 7. 1. 1. 9.]
 [2. 2. 1. 1. 1. 6. 7. 6. 9. 8.]
 [0. 3. 1. 1. 1. 6. 4. 3. 3. 8.]
 [0. 9. 1. 1. 9. 4. 3. 3. 3. 8.]
 [6. 7.

In [ ]:
#Part2